name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
          description: Run by cypress command line
          default: cypress/e2e/*

jobs: 
  cypress-electron-tests-cloud:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Generate timestamp
        id: ts
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron 
          record: true
          group: UI-Electron-${{ env.TIMESTAMP }}
          ci-build-id: CypressCloud-${{ github.run_id }}-${{ env.TIMESTAMP }}-electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-firefox-tests-cloud:
    needs: cypress-electron-tests-cloud
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Generate timestamp
        id: ts
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: firefox 
          record: true
          group: UI-Firefox-${{ env.TIMESTAMP }}
          ci-build-id: CypressCloud-${{ github.run_id }}-${{ env.TIMESTAMP }}-firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
